### PR TITLE
Add threshold possibilities

### PR DESCRIPTION
**Pull request by Napsty**
This PR adds the possibility to define thresholds for an expected number of applications shown to the logged in user.

For example user1 gets a list of 7 applications:

```
$ /usr/lib/nagios/plugins/check_netscaler_gateway.pl -H login.example.com -u user1 -p mypass -S mystore -w 7 -c 7
NetScaler Gateway OK - APP1; Desktop MCP; Desktop Adobe; Desktop-MCP; Desktop-445; APP2; APP3;
```

The threshold matches the number 7 of both warning and critical. 

But user2 gets an empty list but is expected to get at least 4 applications:

```
$ /usr/lib/nagios/plugins/check_netscaler_gateway.pl -H login.example.com -u user2 -p mypass -S mystore -w 4 -c 4
NetScaler Gateway CRITICAL - Only 0 applications found, expected at least 4
```

The tresholds are configured very simple as of now. The number of available applications retrieved from the Netscaler must match or be greater than the treshold(s).

A big improvement to the current situation could be by defining minimum and maximum values for each warning and critical (-w 1:6 -c 0: for example) but I didn't find the time to look into that.

PS: I also increased the version number of the plugin to distinguish. According to your release and my previous commit it should even be 0.0.3. But I let you decide how to increment the version :)

### CODE REVIEW

**Comment by slauger** [comment]
Hi @Napsty,

thank you, great work!

Checking threshold via `min:max` is not that complex. Thanks to our friend sni, we do not have to reinvent the wheel. Monitoring::Plugin already has an function `check_threshold` which does that for us. 

See https://metacpan.org/pod/Monitoring::Plugin#THRESHOLD-METHODS

Do you want to give it a try and update your PR? If you need any help just let me know. Im available via Slack, Skype and Mail.

Otherwise i would at least suggest to use `=<` (greater than or equal to) in instead of `<` for checking the threshold values. In my opinion this is the more common way and would avoid misunderstandings for other users. 

How should we proceed?

Cheers, Simon

**Comment by slauger** [comment]
After merging this i will release a 1.0.0 and push it to the Nagios Exchange.

**Comment by Napsty** [comment]
I actually tried to use monitoring::plugin and use the threshold functions, but was unable to get it to work.

**Comment by slauger** [comment]
Ok. I reviewed this once again and i'm fine with your changes. I'm rebasing this and create a new release.

**Pull request merged**
